version: '3.7'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./hls_streams:/app/hls_streams
    depends_on:
      - nginx_rtmp
    entrypoint: ["python3", "app.py"]
    user: "root" # Ensure backend can write to the volume

  nginx_rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
      - ./hls_streams:/app/hls_streams
    user: "root" # Ensure nginx can read from the volume