version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - nginx_rtmp
    # This is the crucial fix. It tells Docker to run app.py directly.
    entrypoint: ["python3", "app.py"]

  nginx_rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
