"""Add live_stream_url to Drone model

Revision ID: 8ec01ae96dd7
Revises: fd3e8a93d9fd
Create Date: 2025-07-25 17:42:30.888010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec01ae96dd7'
down_revision = 'fd3e8a93d9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('live_stream_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('when', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('place', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('drone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('issue', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_column('issue')
        batch_op.drop_column('region')
        batch_op.drop_column('reason')
        batch_op.drop_column('drone')
        batch_op.drop_column('place')
        batch_op.drop_column('when')

    with op.batch_alter_table('drones', schema=None) as batch_op:
        batch_op.drop_column('live_stream_url')

    # ### end Alembic commands ###
